# change key binding to match screen
unbind C-b
bind C-a send-prefix
set -g prefix C-a

# tmux plugin manager
set -g @plugin 'tmux-plugins/tpm'

# initialize tmux plugin manager (tpm)
run '~/.tmux/plugins/tpm/tpm'

set-option -g history-limit 200000

# shortcut: `:cwd /path/to/dir` to change session default directory
set -s command-alias[10] cwd='attach-session -t . -c'
